name: GardeningTweaks-GriefPrevention
version: '${version}'
main: me.dave.gardeningtweaksclaims.GardeningTweaksClaims
api-version: '1.16'
depend:
  - GardeningTweaks
softdepend:
  - GriefPrevention
  - HuskClaims